### ISSUE TITLE
Mocking stdin for multiple prompts

### ISSUE THREAD

**Issue by open-source-explorer** [sindresorhus/execa#418] opened 2020-04-07 16:12 UTC
Say, I'm writing integration tests for a given feature in a CLI tooling which has got multiple user prompts.

`rootcmd arg` results in couple of prompts-

Do you need X? (Y/N)? Y

Another prompt here (Y/N)? N

> As a result a file is created.

I need to write integration tests in such a way that choices to above prompts are given via the test environment. I can write to `stdin` for the very first prompt in the following fashion:-

```js
const {stdout} = execa(__dirname, args, {input: 'y'});
```

But as said it only works for the very first prompt. How should I be able to do the same for future prompts as well and thereby checking existence for the file?

**Comment by ehmicky** [comment] 2020-04-07 16:23
Hi @open-source-explorer,

I have not tried it locally but would inserting newlines work?

```js
const {stdout} = execa(__dirname, args, {input: 'Y\nN\n'});
```

**Comment by open-source-explorer** [comment] 2020-04-08 05:07
@ehmicky that doesn't seem to work. I was expecting to find something like this one:-

```js
const {stdin, stdout} = execa(__dirname, args, {input: 'y'}); // writes to stdin for the first time.
stdin.write('y'); // writes to stdin for the second time.
stdin.end();
```

**Comment by open-source-explorer** [comment] 2020-04-08 05:10
Also, in the above context the return value from `execa` lacks `stdin`. For instance, 

```js
const subProcess = execa(__dirname, args, {input: 'y', stdio: 'pipe'});
console.log(subProcess.stdin); // undefined
```

Am I doing something wrong?

**Comment by ehmicky** [comment] 2023-12-18 03:30
This is a timing issue.

Namely, once you write the initial `y`, the first prompt processes it. It needs some time before displaying the second prompt and listening for more `stdin` data. Only then, one must write more `stdin` data. I.e. you need to either: 
  - Coordinate between both the logic doing the prompts and the logic writing to `stdin` so they wait for each other
  - Introduce sleep times

Closing as this is not a bug related to Execa.

**Closed by ehmicky** 2023-12-18 03:30 UTC
