### ISSUE TITLE
Intellisense isn't working as expected on execa Options

### ISSUE THREAD

**Issue by tonivj5** [sindresorhus/execa#1154] opened 2024-09-08 16:05 UTC
Hey, I love this library and I'm currently using it in some projects but I've a problem where intellisense isn't working as expected (at least as I expect 😅).

- [Reproduction](https://www.typescriptlang.org/play/?target=9&jsx=0&ts=5.5.4&filetype=ts#code/JYWwDg9gTgLgBAbzgUwB7IMYEMA0cAkcAvnAGZQQhwDkamW1A3AFDN3YAU1MyAzjNTxIA9ACo4AOwhxgEngBt5wXsgkq4AC2RRkcUcOIBKZsIMA9APysx+-BwRjJ02QqUq1urTr3CihgAY8-P4m5hZAA): it's easily reproducible as a typescript playground.
- Here there's other [reproduction](https://www.typescriptlang.org/play/?target=9&jsx=0&ts=5.5.4&filetype=ts#code/JYWwDg9gTgLgBAbzgUQB4FMDGBDAypqYMGXATwDtMBZdGACwgBMAaOAeWOAnIGc5s+AYQggQ3DjC69WZShKl8AvnABmUEXADk6DDk0BuAFChIsRHAAq6cABtsMdLhiFyAczjK1G7buwB6GFIwdB4-EFoGRlCHW3t0ADoAKx4DY3BoeCRZTAAlEIBXG3hPdRAtHSx-QODQqFp8qHI-Op5CmCSUoxMM8ydCTAcoeW4lVVLy3wCgkL9sKFd88PIYUIhOEY7Uw0YsOzq4TBH4AHdgegh8mABJZfQbG2AedF50AC4UX3xCYmyac8YjIZTudLjcHPdHs8ngAKJB+ABUcGAtwhTxecEYEBCcAAcmwLHBjtAANZweF+RQASiMfj8cAAegB+QyGWlwABiwFQcDA6kgPDOUlehh0png1XQH0qAHUznQwXcHminl8iCQKNQIkwADzDXgWaZwHQOchRODCUTida8OAAXnNIjE5D1PAAfHbDHAvXAAGRSnCqn4agBCyMYuutPANwVdnu9frQlUD6soVliDgjkhG0fQscMEv9eAIauyodNmYUOaNqBNZotTpd7ttca92px6GOLqrxueZuyLrtcH7kdd0LWWd473bncjOcprLpeIsyAAhCvvRvN1vtzv6QB9PdweiPOB0AQHM9udCMMYaBDKGAQIcal0tze292JgPFoOUP6RCts0NP1py7aZXUBAsvyLb4U0wNMwDsDMwOCatayER0rQnN0PQ3aF4gImJELiPpkVcd4EKQxxnDI+cdw-Z9KDyVoim1UiBnQIZI0A-VphkF8RwglkdkwPZJUOXgTjlBVUShN5C1legZKVOTk1+LUARZYF5RRFSXlhOAESRXTIXRTFsSJKBiT4ckqRpOkmUMIA) modifying the internals and showing the difference (not working vs working)

<br />

- My current dirty workaround: When I want intellisense what I'm currently doing is modifying the declarations files by hand
	- changing this:
	![image](https://github.com/user-attachments/assets/1ae5d98d-99e1-405c-992e-ded1b03ae0ff)
	- to this:
	![image](https://github.com/user-attachments/assets/7e6e14c0-7367-472a-ad45-03e6fd0346e3)

I don't know why generics are defaulted with `{}` but it seems to break the DX... I expected to find someother posting this issue but nobody, so I suspected initially it could be only on my side 😄 

Best regards for the maintainers, astonish work done here 👏🏻

**Comment by ehmicky** [comment] 2024-09-08 16:17
Hi @tonivj5,

In the playground, Intellisense works for me. Namely, when I start typing `c`, I get a popup with autocompletion suggestion for Execa options: `cancelSignal`, `cleanup`, `cwd`, `gracefulCancel`, and their types. After adding an option, I can get hover it to get its type, although one thing I do see is its documentation. 

The `{}` default does not change to change that behavior, at least on my side.

Do you get a different behavior than that?

**Comment by ehmicky** [comment] 2024-09-08 17:20
It seems like the TypeScript playground behaves a little differently from VSCode. For example, for me, I only get the full documentation when inside VSCode. I am wondering whether there is something to do with the TypeScript config used in the playground. For example, the playground links are showing this in the logs:

```
[ERR]: "Executed JavaScript Failed:" 
[ERR]: import declarations may only appear at top level of a module 
```

Also, the way Execa is used above is not typical: using `declare const withoutIntellisense: ExecaScriptSyncMethod` instead of importing `execaSync` directly. This might potentially give different results.

For the first playground example, you might want to add `await` in front of `execa()` and `$`. I know I've encountered similar (although different) issues with TypeScript when forgetting to `await` Execa.

So this all makes me wonder whether the problem is with the setup or with the types themselves. :thinking: 

Unfortunately, I believe changing the types as you are suggesting would lead to invalid types, considering the default value for `options` is an empty object. Do the type tests still pass after making the type changes you are suggesting?

**Comment by tonivj5** [comment] 2024-09-08 17:38
> It seems like the TypeScript playground behaves a little differently from VSCode. For example, for me, I only get the full documentation when inside VSCode. I am wondering whether there is something to do with the TypeScript config used in the playground.

I comes from vscode, I only used typescript playground as a easy to share reproduction. If you want, I can share a repository with ts setup I'm using

> Also, the way Execa is used above is not typical: using declare const withoutIntellisense: ExecaScriptSyncMethod instead of importing execaSync directly. This might potentially give different results.

it was a way to compare apples with apples in the second reproduction, I actually use `$` and `$.sync`

> Unfortunately, I believe changing the types as you are suggesting would lead to invalid types, considering the default value for options is an empty object. Do the type tests still pass after making the type changes you are suggesting?

I haven't tried it, I only suggested it because it was the "fix" I used, but I didn't know if the use of `{}` was done for a reason.


Checking more cases into vscode I can add this one:
- if there's any option added, intellisense isn't going to work anymore (I only pressed `c` as you mention in your first comment). If no options added yet, it works as you said.
![image](https://github.com/user-attachments/assets/ca737dc3-416f-46ac-bc84-c3fe6f9acfdb)

**Comment by ehmicky** [comment] 2024-09-14 19:11
Thanks for the additional details.

I can reproduce the problem. However, it is unclear whether that's an issue with Execa types, with TypeScript language server, or with VSCode.

Execa is using some pretty advanced types. This has led us to discover (and report) a few bugs in TypeScript itself (that most other projects do not encounter). It seems to me this might be another case.

Unless you can pinpoint specific lines of code in Execa types that are erroneous, I do not know if we can investigate this any further, without delving deeply inside the inner working of VSCode Intellisense.

What do you think @sindresorhus?

**Comment by ehmicky** [comment] 2024-09-16 14:31
:+1: 

Closing this issue then. Sorry @tonivj5!

**Closed by ehmicky** 2024-09-16 14:31 UTC

**Comment by ehmicky** [comment] 2025-07-04 18:51
Hi @simonihmig,

For the reasons [described above](https://github.com/sindresorhus/execa/issues/1154#issuecomment-2351111643), I think this issue should remain closed. However, any PR that fixes this problem (without breaking something else type-wise) is welcome. 👍
