### ISSUE TITLE
execa.shell freezes when command results in stderr

### ISSUE THREAD

**Issue by Wildhoney** [sindresorhus/execa#86] opened 2017-05-04 19:41 UTC
I'm trying to run `postcss` through `execa.shell` but it seems to hang when `postcss` errors:

```javascript
const execa = require('execa');
execa.shell('postcss --use autoprefixer a.css -o b.css', { stdio: 'inherit' });
```

However the equivalent `exec.spawn` from `child_process` results in an **expected** stderr of `ENOENT` because `a.css` does not exist:

```javascript
const exec = require('child_process');
exec.spawn('postcss --use autoprefixer a.css -o b.css', { stdio: 'inherit' });
```

Interestingly it fails silently if I set `stdio` to `ipc`:

```javascript
const execa = require('execa');
execa.shell('postcss --use autoprefixer a.css -o b.css', { stdio: ['ipc', 'inherit', 'inherit', 'inherit'] });
```

Although then we seem to lose the `stdout`.

Any ideas what's going on? As other errors seem to be reported correctly, but when `postcss` errors it just hangs indefinitely.

**Comment by sindresorhus** [comment] 2017-05-07 11:53
Can't reproduce. Worked fine for me on macOS:

```
❯ node x.js
✖ Plugin Error: Cannot find module 'a.css'
```

**Comment by sindresorhus** [comment] 2017-05-07 11:54
Note that `execa.shell` and `exec.spawn` are not the same thing.

**Comment by Wildhoney** [comment] 2017-05-07 13:55
Thanks @sindresorhus 

It seems to be an issue with `postcss` because the latest version works for me, as it did for you. However with `postcss-cli@2.5.2` it hangs.

Please confirm you receive the same with `v2.5.2` and close if you think it's necessary.

**Comment by sindresorhus** [comment] 2017-05-07 14:48
> Please confirm you receive the same with v2.5.2

Yes, it hangs.

---

Closing as it works with latest `postcss-cli`.

**Closed by sindresorhus** 2017-05-07 14:48 UTC
