### ISSUE TITLE
Error TS2834 - Relative import paths need explicit file extensions in ECMAScript

### ISSUE THREAD

**Issue by qmonmert** [sindresorhus/execa#1036] opened 2024-05-09 10:23 UTC
Since `9.0.0`, I have:
```
node_modules/execa/index.d.ts:6:8 - error TS2834: Relative import paths need explicit file extensions in ECMAScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Consider adding an extension to the import path.

6 } from './types/stdio/type';
         ~~~~~~~~~~~~~~~~~~~~

node_modules/execa/index.d.ts:7:41 - error TS2834: Relative import paths need explicit file extensions in ECMAScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Consider adding an extension to the import path.

7 export type {Options, SyncOptions} from './types/arguments/options';
                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/execa/index.d.ts:8:39 - error TS2834: Relative import paths need explicit file extensions in ECMAScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Consider adding an extension to the import path.

8 export type {Result, SyncResult} from './types/return/result';
                                        ~~~~~~~~~~~~~~~~~~~~~~~

node_modules/execa/index.d.ts:9:46 - error TS2834: Relative import paths need explicit file extensions in ECMAScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Consider adding an extension to the import path.

9 export type {ResultPromise, Subprocess} from './types/subprocess/subprocess';
                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/execa/index.d.ts:11:42 - error TS2834: Relative import paths need explicit file extensions in ECMAScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Consider adding an extension to the import path.

11 export {ExecaError, ExecaSyncError} from './types/return/final-error';
                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/execa/index.d.ts:12:21 - error TS2834: Relative import paths need explicit file extensions in ECMAScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Consider adding an extension to the import path.

12 export {execa} from './types/methods/main-async';
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/execa/index.d.ts:13:25 - error TS2834: Relative import paths need explicit file extensions in ECMAScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Consider adding an extension to the import path.

13 export {execaSync} from './types/methods/main-sync';
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/execa/index.d.ts:14:46 - error TS2834: Relative import paths need explicit file extensions in ECMAScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Consider adding an extension to the import path.

14 export {execaCommand, execaCommandSync} from './types/methods/command';
                                                ~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/execa/index.d.ts:15:17 - error TS2834: Relative import paths need explicit file extensions in ECMAScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Consider adding an extension to the import path.

15 export {$} from './types/methods/script';
                   ~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/execa/index.d.ts:16:25 - error TS2834: Relative import paths need explicit file extensions in ECMAScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Consider adding an extension to the import path.

16 export {execaNode} from './types/methods/node';
                           ~~~~~~~~~~~~~~~~~~~~~~


Found 10 errors in the same file, starting at: node_modules/execa/index.d.ts:6
```

My `tsconfig.json` has:
```
    "module": "node16" /* Specify what module code is generated. */,
    "rootDir": "./" /* Specify the root folder within your source files. */,
    "resolveJsonModule": true,
```

An idea to fix that? Thanks a lot

**Comment by cedx** [comment] 2024-05-09 11:08
Duplicate of #1031, fixed in #1033.
We'll just have to wait for the release of a new version on `npm`.

**Comment by qmonmert** [comment] 2024-05-09 12:09
@cedx ok thanks

**Comment by sindresorhus** [comment] 2024-05-09 17:10
https://github.com/sindresorhus/execa/releases/tag/v9.0.1

**Closed by sindresorhus** 2024-05-09 17:10 UTC
