### ISSUE TITLE
Unable to extend env when `ProcessEnv` has been manipulated

### ISSUE THREAD

**Issue by ehyland** [sindresorhus/execa#1132] opened 2024-06-26 21:48 UTC
When a non optional property has been defined on `ProcessEnv` by [interface merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html#merging-interfaces), it is not possible to use execa's `env` & `extendEnv` options to add additional environment variables to execa process. 

[Typescript playground example](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzgUwB7IMYEM4F84BmUEIcA5GplmQNwCwAUKJLOQAJTIjCoC0UAVwB2AeiEQAJsjKNGIgFSMAKgAtgAZ0JZgAG01ZNHLj37Cxk5ClQxkQiZpgrLABWIZk69QFEhANzjAQjZQBFjusgwiIoTEpEbcfIKi4lKMgcGh7nCuEO6ePv4IjHBwAHIA8gAiXgD6XqUAagBccABEUr7IOhBgILYwrXAAPm1gxBICGDDAEEKDI6026gP0DLiM8iIRjBizy3AAJHAAvFZUABRFDCXLEjMtrYFOUMADADTFVjZ2BS0wgsgPtcUH4WlcSiVKgBBJRQgBCUIAyrUAKoAJQAMi0yNDYQjkTV0RiyECSrggbgAJSrCJYADu2ngBwABmMNCAcBIAEZwMACdQqOC8XhhdxgGC8CRYGBYXjdTzMmkMIA) 

## Example

```ts
import { config } from "~/config.server";
import { execa } from "execa";

// from @remix-run/node
interface ProcessEnv {
  NODE_ENV: "development" | "production" | "test";
}

// attempting to extend process env results in TS error "No overload matches this call."
const $ = execa({
  stdio: "inherit",
  extendEnv: true,
  env: {
    DATABASE_URL: config.DATABASE_URL,
  },
});

await $`prisma db push --accept-data-loss`;
``` 

## Suggestion

Instead of [`env` option](https://github.com/sindresorhus/execa/blob/6c6e8611a7834f52be9070b3de29e4de466acfc8/types/arguments/options.d.ts#L80) being typed as `typeof import('node:process').env`. Maybe it should be typed as `Record<string, string | undefined>`

**Comment by ehmicky** [comment] 2024-06-27 00:00
Hi @ehyland,

This seems to be a bug with `@remix-run/node`, not Execa. Namely, the same behavior happens when using `node:child_process` instead of Execa ([TypeScript playground](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbwM5gIYHcB2BfOAzKCEOAckwgBMBTALgGMALYAGwoH0xC6qkkSBuALAAoUJFhwARAAEoVEMAAeAWigBXTAHpy1SUOEiUGTAAoSVRhBIAaOAG1zi1OGZUSAXVsIRcOFUwAbjSIPr5wACIAggAqkQBCkQDKAKJsAKoASgAywSRRsQkp6dkkodgi2ACU-EA)).

```ts
import {spawn} from 'node:child_process';
import "@remix-run/node";

spawn('echo', ['example'], {
  env: {
    DATABASE_URL: 'DATABASE_URL'
  }
});
```

```
No overload matches this call.
  The last overload gave the following error.
    Property 'NODE_ENV' is missing in type '{ DATABASE_URL: string; }' but required in type 'ProcessEnv'.
```

The problem is: the interface merging done by `@remix-run/node` is making `NODE_ENV` a required property. Your example above is not defining `env.NODE_ENV`, therefore typing fails, but that's the expected behavior from the additional constraint Remix is adding.

I would suggest one of the following:
  - Posting an issue on `@remix-run` to make `NODE_ENV` optional. They probably need to use both `?` and `... | undefined` to follow how Node.js types `ProcessEnv`.
  - Adding `env.NODE_ENV` to your code.
  - Workaround using the following:

```ts
import { execa, type Options } from 'execa';
import '@remix-run/node'

const $ = execa({
  stdio: "inherit",
  extendEnv: true,
  env: {
    DATABASE_URL: 'DATABASE_URL'
  } as unknown as Options['env'],
});
```

**Comment by ehmicky** [comment] 2024-07-02 16:55
@ehyland Did this fix your issue?

**Comment by ehyland** [comment] 2024-07-03 05:32
Hi @ehmicky, thanks for your response there

I got around this by setting `NODE_ENV` in `options.env`.

I can see this from both sides. While I would prefer they did not extend `ProcessEnv`, I don't think it's entirely incorrect.

In the remix app environment that they control `NODE_ENV` will always be set.

But it has an unintended consequence that if for some reason you want to define `ProcessEnv`, you now have to provide `NODE_ENV`.

Given the execa APIs `env` option is designed for extending the current process environment. Might it be more correct to type the option as `Partial<ProcessEnv>`?

**Comment by ehmicky** [comment] 2024-07-03 16:59
Node.js uses `ProcessEnv` to define both `process.env` and the `env` option of `child_process.spawn()`. Even if `process.env.NODE_PATH` is always defined in Remix, typing `ProcessEnv["NODE_PATH"]` as required means that `env.NODE_PATH` must always be passed to `child_process.spawn()`, which was probably not intended by Remix.

As mentioned above, this problem is not specific to Execa: the same issue happens with `child_process.spawn()`. So that's definitely not something that should be fixed in Execa.

**Closed by ehmicky** 2024-07-03 16:59 UTC

**Comment by ehyland** [comment] 2024-07-04 08:00
Yeah okay, makes sense to follow `child_process` module types. Thanks for the support @ehmicky

**Comment by ehmicky** [comment] 2024-07-05 23:04
I created an issue at https://github.com/remix-run/remix/issues/9718

**Comment by ehmicky** [comment] 2024-08-09 22:10
We're working on providing with a patch for this issue at https://github.com/sindresorhus/execa/pull/1141
