### ISSUE TITLE
Subprocess is considered as failed exit when using `process.kill` on windows only

### ISSUE THREAD

**Issue by huang-julien** [sindresorhus/execa#1102] opened 2024-05-26 21:01 UTC
# Reproduction

https://github.com/huang-julien/execa-repro

## Steps

- clone it on windows
- run index.js with WSL
- it exit after 5 sec without issue
- run again but with powershell or cmd
- it crash after 5 sec (terminated with SIGTERM)

# Description 

Hello :wave:

This is an issue we detected on https://github.com/nuxt/test-utils/pull/848

On windows, with using `process.exit()` without exitCode, the exitCode received by execa is `null` while it is `0` on linux.

**Comment by ehmicky** [comment] 2024-05-26 21:39
Hi @huang-julien,

Thanks for reporting this!

I cannot easily setup WSL on my machine, so we might need a few back-and-forth going through your reproduction example. Thanks for putting this up!

My first question would be: does the example reproduce without setting up the HTTP server?

**Comment by huang-julien** [comment] 2024-05-26 21:59
I reduced the repro with a simple timeout :) . 

WSL isn't mandatory, you can use linux. It's just that I don't have dual boot linux/windows 😅 

Weirdly, execa receive `0` and `null` for exitCode and signal in WSL/linux but gets `null` and `'SIGTERM'` in windows

**Comment by ehmicky** [comment] 2024-05-27 00:50
Thanks!

What's happening is the following: Windows does not support Unix-style signals. Node.js emulates a handful of signals, but it has some limitations. You can find more details [here](https://nodejs.org/api/process.html#signal-events) and [there](https://github.com/ehmicky/cross-platform-node-guide/blob/main/docs/6_networking_ipc/signals.md#cross-platform-signals). This behavior is inherited by Execa since we rely on Node.js `child_process` core module.

Links to the code: 
  - Node.js: [here](https://github.com/nodejs/node/blob/ff659faeb8858a9fba70027ccfb1a0251fd64e1f/lib/internal/child_process.js#L499), which forwards to libuv [there](https://github.com/nodejs/node/blob/ff659faeb8858a9fba70027ccfb1a0251fd64e1f/src/process_wrap.cc#L315)
  - libuv: 
     - on [Unix](https://github.com/libuv/libuv/blob/d2d92b74a8327daf9652a9732454937f3529bd30/src/unix/process.c#L1082), it calls the [`kill` syscall](https://www.man7.org/linux/man-pages/man2/kill.2.html)
     - on [Windows](https://github.com/libuv/libuv/blob/d2d92b74a8327daf9652a9732454937f3529bd30/src/win/process.c#L1354), it calls the [`TerminateProcess`](https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-terminateprocess) Win32 API method [here](https://github.com/libuv/libuv/blob/d2d92b74a8327daf9652a9732454937f3529bd30/src/win/process.c#L1294) 

So, on Windows, `process.on('SIGTERM')` is a noop. You should be able to experience this yourself by looking at the `stdout` property on the Execa result, which should contain `'SIGTERM signal received'` when using WSL, but not when using `cmd.exe` or Powershell.

On Unix (or WSL), `process.on('SIGTERM')` is run, and since you call `process.exit()`, the subprocess has a successful exit, which means `exitCode` is `0` and `signal` is `undefined`. On Windows (non-WSL), `process.on('SIGTERM')` is not run, and the subprocess is terminated right away, which means `exitCode` is `undefined` and `signal` is `'SIGTERM'`.

This is expected behavior. The difference is due to the fact that Unix and Windows implement IPC differently. Node.js/libuv does some work to try to bridge those differences, but it is unfortunately limited.

The reason this behavior is now showing up with Execa 9 and not 8 is probably due to a bug fix landed by Execa 9. We fixed a bunch of related bugs in that release, and it's possible the new behavior, which is the correct one, might have been previously erroneous.

So this does not seem to be a bug. That being said, if you give me more information about what you're trying to achieve, I'm happy to give you some advice on how to upgrade to Execa 9. For example, if you'd like to do a graceful exit in a way that works cross-platform, I would recommend using [Node.js IPC](https://github.com/sindresorhus/execa/blob/v9.1.0/docs/ipc.md) instead. We are about to release a bunch of IPC-related features in the coming days.

**Comment by ehmicky** [comment] 2024-06-03 18:32
@huang-julien Based on the above, do you think this issue should be closed, or is there something else that you think might be a pending bug?

**Comment by huang-julien** [comment] 2024-06-04 07:19
This would be wonderful, thank you !

We still have a process pending with `subprocess.kill(0)` but i think it may be worth checking that after the upcoming release. This issue can probably closed.

**Closed** 2024-06-04 17:19 UTC

**Comment by ehmicky** [comment] 2024-06-06 18:17
The new features mentioned in my previous comment have just been released in [`9.2.0`](https://github.com/sindresorhus/execa/releases/tag/v9.2.0).
