### ISSUE TITLE
How to prevent broken pipe (SIGPIPE)

### ISSUE THREAD

**Issue by xpuu** [sindresorhus/execa#1155] opened 2024-09-16 14:08 UTC
First of all, thank you for your work. I've already spent quite a few hours reading the documentation, discussions, and some code. It's a remarkable research project that truly enhances programming experience in the Node.js ecosystem.

I'm writing various scripts to back up and sync databases, handling complex pipes, and processing gigabytes of data. For many reasons, I'm trying to avoid using the 'shell' option for execution. So far, this approach has worked well for me. However, I've been struggling with preventing the 'broken pipe' issue. I'll try to illustrate this with the following example:

```shell
# Broken pipe
openssl rand -hex 1 | tee >(wc -c > size) | head -c0; echo "${PIPESTATUS[@]}"; cat size
0 141 0   # pipestatus
0         # wrong wc output

# Broken pipe and complaining openssl
$ openssl rand -hex 10000 | tee >(wc -c > size) | head -c0; echo "${PIPESTATUS[@]}"; cat size
1 141 0   # pipestatus
0         # wrong wc output

# Broken pipe prevented
openssl rand -hex 1 | tee >(wc -c > size) | { head -c0; cat > /dev/null; }; echo "${PIPESTATUS[@]}"; cat size
0 0 0     # pipestatus
3         # correct wc output
```
By using `{ head -c0; cat > /dev/null; }`, I ensure that the stdout of openssl is not closed prematurely, which prevents a broken pipe. However, when using Execa, I get unexpected results.
```javascript
// This works fine
const cmd = execa('openssl', ['rand', '-hex', '10000'], { buffer: { stdout: false, stderr: true } })
console.log(await Promise.all([cmd.pipe`wc -c`, cmd.pipe`head -c0`]))

// Increasing openssl output results in exception
// ExecaError: Command failed with exit code 1: openssl rand -hex 100000
const cmd = execa('openssl', ['rand', '-hex', '100000'], { buffer: { stdout: false, stderr: true } })
console.log(await Promise.all([cmd.pipe`wc -c`, cmd.pipe`head -c0`]))
```
Is there any way to prevent this issue? Thanks.

**Comment by ehmicky** [comment] 2024-09-16 15:17
Hi @xpuu,

To start, I wonder: what is the purpose of `head -c0`? Does not it ask to retrieve the first 0 bytes of `stdin`, i.e. always print nothing? Maybe it's just for example purpose?

When `head` is reaching the amount of bytes requesting by the `-c` flag, it stops the pipeline by sending a `SIGPIPE` to the previous command (here `tee`). The previous command can handle `SIGPIPE`, but in general it does not, and the OS default behavior then is to terminate that command.

You can experience this yourself using the following example. 

```
$ openssl rand -hex 10000 | head -c1; echo -e "\n${PIPESTATUS[@]}";
1 0
```

By decreasing or increasing `10000`, you will sometimes get `0 0`, and sometimes `1 0`. That's because OS signals take some time to be sent and received by the OS. This leads to a race condition: sometimes `openssl` terminates fast enough, before receiving the `SIGPIPE`, sometimes afterwards, depending on timing conditions and how big the input/output is.

Since `SIGPIPE` is used for the above purpose, Execa chooses to purposely not consider it an error.

https://github.com/sindresorhus/execa/blob/3fc804916d60b0b2e774a3642bd9815388caf7af/lib/resolve/wait-stream.js#L91-L96

But it cannot prevent that, once `head` has closed its `stdin`, `openssl` will keep trying to write to it, leading to an `EPIPE` error. That's actually how Unix pipelines were designed for that type of command, I believe. When this happens, `openssl` exits with a non-0 exit code, which means it also stops writing to `wc -c`, which is your problem.

I think the core of the problem is that, the way Unix pipelines are designed, you're probably supposed to do: `openssl -> head -> wc`, as opposed to `openssl -> wc` + `openssl -> head`. In other words:

```js
console.log(await execa('openssl', ['rand', '-hex', '10000'], { buffer: { stdout: false, stderr: true } }).pipe`head -c0`.pipe`wc -c`)
```

It seems like the subshell `{ head -c0; cat > /dev/null; }` is somehow working around this, but that's arguably a hack. Also, being a subshell, it requires using a shell, i.e. would need the `shell` option.

So it looks like the core of the problem is a misunderstanding on how termination and input/output propagates across the pipeline. The good news is that using the above example (with `openssl -> head -> wc` might work for your use case thanks to Execa showing you the intermediate result of each command as [part of `result.pipedFrom`](https://github.com/sindresorhus/execa/blob/main/docs/pipe.md#result), so you will get: 1) the full output of `openssl`, 2) the truncated output of `openssl -> head`, 3) the amount of bytes of that truncated output.

**Comment by mkicks** [comment] 2024-09-16 16:12
Hi, thanks for the prompt reply. Here's the actual situation:

Database dump (and from its piped stdout)
- Counting the size of the uncompressed output for later reference
- Compressing it to the filesystem
- Immediately restoring it to another database server

The last two processes are likely to fail (e.g., no space left on the filesystem, database is down, etc.). Ideally, I wouldn’t want any of these errors to stop the other processes.

**Comment by ehmicky** [comment] 2024-09-24 20:53
@xpuu @mkicks Should we close this issue?

**Comment by xpuu** [comment] 2024-09-26 14:59
Many thanks for your insights. I still have some questions on the topic, but I don’t have time this week to really delve into it. If I’m not able to write more next week, please go ahead and close the topic.

**Comment by ehmicky** [comment] 2024-09-26 16:58
No problem @xpuu. Please feel free to open a separate issue for new questions. :+1:

**Closed by ehmicky** 2024-09-26 16:58 UTC

**Comment by xpuu** [comment] 2025-10-25 08:42
I finally found a workaround for the broken pipe (SIGPIPE) issue when multiple consumers read from the same stdout. When one of the piped commands (like head) exits early, it closes the shared stream and causes the source process to fail. To avoid that, you can duplicate the stdout using PassThrough streams so each consumer has its own independent reader:

```javascript
const exe = execa({ verbose: 'short' })
const exenb = exe({ buffer: { stdout: false, stderr: true } })

// Source
const cmd = exenb('openssl', ['rand', '-hex', '100000'])

// Helper
function pass(stream) {
  return {
    attach() {
      const p = new PassThrough()
      stream.pipe(p)
      return p
    }
  }
}

const src = pass(cmd.stdout)

const res = await Promise.all([
  exe('wc', ['-c'], { input: src.attach() }),
  exe('head', ['-c0'], { input: src.attach() }),
])
```

Instead of sharing a single pipe (which can close early and trigger SIGPIPE), create multiple PassThrough clones. Each consumer reads from its own copy, keeping the upstream stream alive until all consumers finish.
