### ISSUE TITLE
Bundled typescript definitions not available from npm?

### ISSUE THREAD

**Issue by tommedema** [sindresorhus/execa#206] opened 2019-04-17 18:05 UTC
I used to depend on `@types/execa` but now need to use the new `.cancel()` function which is not documented there.

Fortunately `execa` now seems to bundle its [own type definitions](https://github.com/sindresorhus/execa/blob/master/index.d.ts).

However when installing just execa (at least with `yarn add execa`) these type definitions are lost:

![Screen Shot 2019-04-17 at 11 03 07 AM](https://user-images.githubusercontent.com/331833/56310381-9dfcde80-6100-11e9-8168-76f6709721f1.png)
![Screen Shot 2019-04-17 at 11 03 05 AM](https://user-images.githubusercontent.com/331833/56310382-9dfcde80-6100-11e9-97d5-d988afbdf290.png)

This is with execa@1.0.0.

**Comment by sindresorhus** [comment] 2019-04-17 18:24
Duplicate of #204

**Closed by sindresorhus** 2019-04-17 18:24 UTC

**Comment by tommedema** [comment] 2019-04-17 18:31
I see .cancel is not yet implemented but are the bundled typings not supposed to work?

**Comment by ehmicky** [comment] 2019-04-17 18:47
I think what @sindresorhus meant is that this is not released to npm yet.
