### ISSUE TITLE
feat: setting column on spawned process

### ISSUE THREAD

**Issue by privatenumber** [sindresorhus/execa#459] opened 2021-05-21 06:54 UTC
## Feature request
Would like to be able to specify the `column` and `rows` for the stdout of the spawned process.

## Motivation
I'm using execa to spawn a command that is printing text that is wrapped. It doesn't wrap when I run it directly or if I set `stdio: 'inherit'`.

**Comment by sindresorhus** [comment] 2021-05-21 07:16
This is not possible. There's no `column` / `row` on the spawned process. You need a PTY for that, like https://github.com/microsoft/node-pty

See this Node.js issue: https://github.com/nodejs/node/issues/31409

I agree, it would be very useful.

**Comment by privatenumber** [comment] 2021-05-21 07:33
Ah I see. That's a shame...

Thanks for those links. Upvoted the Node.js issue—let me know if there's anything else I can do to help push for it.

I was experimenting and I saw I could pass in `new tty.WriteStream(1)` as the `stdout` and it would work fine but print to the actual stdout (so basically I was just inheriting the stdout).

I'm not very good with streams/tty, so excuse me if I'm just completely off, but I was wondering if it's possible to pass in a fake tty write stream that just collects the output. Probably not though if it's just a wrapper for the [internal tty binding](https://github.com/nodejs/node/blob/50f076c4f59bbaaf129e858abfe8327b64d1113c/lib/tty.js#L31).

**Comment by sindresorhus** [comment] 2021-05-21 11:48
> but I was wondering if it's possible to pass in a fake tty write stream that just collects the output. Probably not though if it's just a wrapper for the internal tty binding.

Not as far as I know, but it's been years since I tried to do something like that.

**Comment by ehmicky** [comment] 2023-12-18 03:20
Closing as the issue is not related to Node.js.

**Closed by ehmicky** 2023-12-18 03:20 UTC
