### ISSUE TITLE
'signals' of undefined

### ISSUE THREAD

**Issue by tibdev78** [sindresorhus/execa#453] opened 2021-03-21 18:06 UTC
Hello,

I tried to use your package to run a shell command through my vue project and I get this: 
```
Unable to read the 'signals' property of undefined

```

that i tried :
```
 const {stdout} = await execa('ls')
      console.log(stdout)
```
I think this is interfering with the signal from wds that use vue.
Can you fix it please?

**Comment by sindresorhus** [comment] 2021-03-22 06:22
This is a Node.js package. Most issues like these are caused by a bundler, not the package itself. I'm closing this for now, but if you submit a failing test, I'll take a closer look.

**Closed by sindresorhus** 2021-03-22 06:23 UTC
