### ISSUE TITLE
Unfinished execa promise when path is not found and buffer=false

### ISSUE THREAD

**Issue by tiagonapoli** [sindresorhus/execa#350] opened 2019-07-13 16:41 UTC
When running:
```javascript
const proc = await execa("echo hello", [], {
  buffer: false
});
```
This promise never resolves or rejects. 

I investigated the source and found the problem on:
https://github.com/sindresorhus/execa/blob/071a8154f882d13116a6a91d8691ea150de31753/lib/stream.js#L60-L67

And fixed using:
```javascript
if (!buffer) {
    // TODO: Use `ret = util.promisify(stream.finished)(stream);` when targeting Node.js 10
    return new Promise((resolve, reject) => {
        stream
            .once('end', resolve)
            .once('error', reject)
            .once('close', resolve)
    });
}
```
Adding `.once('close', resolve)` solved the problem, since when the file is not found, it seems `child_process.spawn` just closes the streams but not writes an end (?).

The solution proposed by the TODO comment works too, but I had a doubt about the `targeting Node.js 10` part: The project is dropping compatibility with previous versions?

 Another problem about the buffer option that I noticed is in the documentation:

> #### buffer
> Type: `boolean`<br>
> Default: `true`
> 
> Buffer the output from the spawned process. When buffering is disabled you must consume the output of the `stdout` and `stderr` streams because the promise will not be resolved/rejected until they have completed.
> 

Consuming the `stdout` and `stderr` is not enough, the `all` stream has to be consumed too, or just resumed. (consuming only the `all` stream works too)

I would be glad to open a PR to fix these issues

**Comment by ehmicky** [comment] 2019-07-13 18:06
Hi @tiagonapoli,

Thanks for reporting this. I'm very happy someone is finally tackling this problem.

First: `execa("echo hello", [])` won't work, you need to use either `execa("echo", ["hello"])` or `execa.command("echo hello")`. Or maybe you intended to make that mistake to trigger a "file not found" error?

> Adding .once('close', resolve) solved the problem, since when the file is not found, it seems child_process.spawn just closes the streams but not writes an end (?).

Is this only for the case when a "file not found" error is triggered? I can reproduce the original problem (promise not resolving when `buffer` is `false`) even with a normal command.

> The solution proposed by the TODO comment works too, but I had a doubt about the targeting Node.js 10 part: The project is dropping compatibility with previous versions?

We are supporting Node `>=8`. In 1 year we will drop Node 8 (like core Node.js itself), then we'll be able to use `util.promisify(stream.finished)(stream)`.

> Consuming the stdout and stderr is not enough, the all stream has to be consumed too, or just resumed. (consuming only the all stream works too)

Could you please provide an example that fails? The `all` stream is a little tricky and different from `stdout` and `stderr`. I'm not sure it does need to be consumed.

**Comment by tiagonapoli** [comment] 2019-07-13 18:31
> First: execa("echo hello", []) won't work, you need to use either execa("echo", ["hello"]) or execa.command("echo hello"). Or maybe you intended to make that mistake to trigger a "file not found" error?

Oh, sorry, I didn't mentioned this, the mistake was intended.

> Is this only for when a "file not found" error is triggered? I can reproduce the original problem (promise not resolving when buffer is false) even with a normal command.

https://github.com/sindresorhus/execa/blob/071a8154f882d13116a6a91d8691ea150de31753/lib/stream.js#L77-L92

In the source code, the execa promise only resolves or rejects when `stdout`,`stderr` and `all` streams are done. When `buffer=false` these promises are done when `'end'` or `'error'` events are emitted by the streams. In order to `'end'` be emitted by these streams, which are `Stream.Readable`, i think they have to be in flowing state. So all three have to be flowing. The `all` stream is created using `merge-stream`. I think when you run `.all.resume()`, `merge-stream` resumes both `stdout` and `stderr`, granting that all three streams will end.
When you resume `stdout` and `stderr` I think `all` is not resumed too, so `stdout` and `stderr` emit end event, but `all` doesn't, so the execa promise doesn't resolve.

I made the following examples to test these behaviors:
```javascript
const execa = require("execa");

(async () => {
  const proc = execa("echo", ["hello"], { buffer: false });
  proc.all.resume();
  //The promise resolves
  const procRes = await proc;
  console.log("done", procRes);
})();
```

```javascript
const execa = require("execa");

(async () => {
  const proc = execa("echo", ["hello"], { buffer: false });
  proc.stdout.resume();
  proc.stderr.resume();
  // This never gets printed
  const procRes = await proc;
  console.log("done", procRes);
})();
```

**Comment by tiagonapoli** [comment] 2019-07-13 18:57
I made an experiment with `child_process.spawn`, which is used to spawn the process and the 'end' and 'close' events are emitted:
```javascript
const { spawn } = require("child_process");

const addEv = (stream, ev, msg) => {
  stream.on(ev, () => {
    console.log(msg);
  });
};

(async () => {
  // error intended
  const proc = spawn("echo hello");

  //end is emitted
  addEv(proc.stdout, "end", "stdout end");
  //close is emitted
  addEv(proc.stdout, "close", "stdout close");
  //error is not emitted
  addEv(proc.stdout, "error", "stdout error");

  //end is emitted
  addEv(proc.stderr, "end", "stderr end");
  //close is emitted
  addEv(proc.stderr, "close", "stderr close");
  //error is not emitted
  addEv(proc.stderr, "error", "stderr error");

  proc.on("error", err => {
    // proc emits ENOENT
    console.log("proc error", err);
  });

  proc.on("close", () => {
    // proc closes
    console.log("process ended");
  });
})();
```

Could some kind of race condition the reason that the 'end' event is not caught?

**Comment by tiagonapoli** [comment] 2019-07-13 21:01
I was able to find out why the `end` event was not emitted in this case and, because of this, the promise was not resolved/rejected:

```javascript
const execa = require("execa");

(async () => {
  // intended error. Apparently because of this ENOENT the stderr and stdout are straight closed, but not ended
  const proc = execa("echo hello", { buffer: false });
  proc.stderr.on("end", () => {
    // stderr is not ended
    console.log("end stderr");
  });

  proc.stdout.on("end", () => {
    // stdout is not ended
    console.log("end stdout");
  });

  proc.all.on("end", () => {
    // all is ended
    console.log("end all");
  });

  proc.stderr.on("close", () => {
    // stderr is closed
    console.log("close stderr");
  });

  proc.stdout.on("close", () => {
    // stdout is closed
    console.log("close stdout");
  });

  proc.all.on("close", () => {
    // all is closed
    console.log("close all");
  });

  proc.stderr.resume();
  proc.stdout.resume();
  proc.all.resume();
  // This never gets printed probably because the 'end' event is not emitted, i dont know why. The close event is emmitted though
  const procRes = await proc;
  console.log("done", procRes);
})();
```

I tracked down the error to this:
https://github.com/sindresorhus/execa/blob/071a8154f882d13116a6a91d8691ea150de31753/lib/stream.js#L82-L91

When the spawned process emits the `ENOENT` error, the `processDone` is rejected. Then `getBufferedData` enters in action:
https://github.com/sindresorhus/execa/blob/071a8154f882d13116a6a91d8691ea150de31753/lib/stream.js#L41-L53

But it destroys the stream before the `end` event was emitted, then only the `close` event is. I don't know when the` end` event is emitted in the `child_process` lifetime, but it is eventually, at least on this case (if the `stream.destroy()` line is deleted the `end` event is emitted)

**Comment by ehmicky** [comment] 2019-07-14 10:30
Thanks a lot for digging deep into this issue! 

For reference, the [`all` stream](https://github.com/grncdr/merge-stream/blob/master/index.js) is a `PassThrough`, and `stdout` and `stderr` both (separately) pipe to it:

```
stdout --> all
stderr --> all
```

`all.end()` is called if both `stdout` and `stderr` emit `end` or `unpipe`. `all` emits `error` if either `stdout` and `stderr` emits `error`, which I think should close it.

I am a little confused about `resume()`: looking at [`merge-stream`](https://github.com/grncdr/merge-stream/blob/master/index.js) code, do you know why `all` is not in flowing mode? Doesn't piping things into a stream put it in flowing mode? Should we always call `all.resume()` to ensure this?

For the "promise not resolved" problem: I looked at [Node.js `finished()`](https://github.com/nodejs/node/blob/master/lib/internal/streams/end-of-stream.js) implementation. They also listen to `close` and `finished` events. The following code seems to fix your issue (based on your investigation and suggestion solutions):

```js
if (!buffer) {
    // TODO: Use `ret = util.promisify(stream.finished)(stream);` when targeting Node.js 10
    return new Promise((resolve, reject) => {
        stream
            .once('end', resolve)
            .once('close', resolve)
            .once('finished', resolve)
            .once('error', reject)
    });
}
```

Node.js `finished()` is a copy/paste from [`end-of-stream`](https://github.com/mafintosh/end-of-stream/blob/master/index.js), so ideally we should use `end-of-stream` as a polyfill for it until we drop support for Node 8.

**Comment by tiagonapoli** [comment] 2019-07-14 15:13
> I am a little confused about resume(): looking at merge-stream code, do you know why all is not in flowing mode? Doesn't piping things into a stream put it in flowing mode? Should we always call all.resume() to ensure this?

When you mentioned this I started to get confused too, so i investigated a little:

I added this code to `makeAllStream` function:
```javascript
	const mixed = mergeStream();
	mixed.on("close", () => console.log("mixed close"));
	mixed.on("error", () => console.log("mixed error"));
	mixed.on("finish", () => console.log("mixed finish"));
	mixed.on("pipe", () => console.log("mixed pipe"));
	mixed.on("unpipe", () => console.log("mixed unpipe"));
	mixed.on("end", () => console.log("mixed end"));
```

Making a simple test with:
```javascript
(async () => {
	try {
		const proc = execa("echo", ["hello"], { buffer: false });
		// This never gets printed
		const procRes = await proc;
		console.log("done");
	} catch (err) {
		console.log("main err", err);
	}
})();
```

The output was:
```
mixed pipe
mixed pipe
mixed unpipe
mixed finish
mixed unpipe
```
The `mixed` stream is a `Duplex` stream, so it's at the same time `Readable` and `Writable`. When piping `stdout` and `stderr` to `mixed`, it's acting like a `Writable`, so the `end` event is not emitted, since `end` is a `Readable` event, instead the `finish` event is emitted. The `close` event is not emitted too, but that I think is because some technicality about `Duplex` streams or the `merge-stream` package: I haven't used `Duplex` yet, so i don't know much about it, these are just my theories. 
Since `end` nor `close` events are emitted, the `allStreamPromise` is not resolved. When doing `all.resume()` (which was the workaround i proposed) I think it triggers the `Readable` behavior of the `Duplex`, then `end` and `close` events are emitted, when the `Readable` side of the `Duplex` is done with data.

I checked if it's necessary to execute `stdout.resume` and `stderr.resume`, but it's not, only the `allStreamPromise` is unresolved. Adding event listeners right after creating the `spawned` process shows that they're ended and closed correctly:
```javascript
spawned = childProcess.spawn(parsed.file, parsed.args, parsed.options);
spawned.stdout.on("close", () => console.log("stdout close"));
spawned.stdout.on("error", () => console.log("stdout error"));
spawned.stdout.on("end", () => console.log("stdout end"));

spawned.stderr.on("close", () => console.log("stderr close"));
spawned.stderr.on("error", () => console.log("stderr error"));
spawned.stderr.on("end", () => console.log("stderr end"));
```

**Comment by tiagonapoli** [comment] 2019-07-14 22:34
> ```javascript
> if (!buffer) {
>     // TODO: Use `ret = util.promisify(stream.finished)(stream);` when targeting Node.js 10
>     return new Promise((resolve, reject) => {
>         stream
>             .once('end', resolve)
>             .once('close', resolve)
>             .once('finished', resolve)
>             .once('error', reject)
>     });
> }
> ```

How about using [end-of-stream](https://www.npmjs.com/package/end-of-stream)? `Stream.finished` from node is based on it. Then the usage could be something like:
```javascript
const eos = require("end-of-stream");
const mergeStream = require("merge-stream");
const { spawn } = require("child_process");

const getStreamPromise = (stream, eosOpts) => {
  return new Promise((resolve, reject) => {
    let cleanListeners;
    const cb = err => {
      if (err) reject(err);
      resolve();
      cleanListeners();
    };

    if (eosOpts) cleanListeners = eos(stream, eosOpts, cb);
    else cleanListeners = eos(stream, cb);
  });
};

(async () => {
  const spawned = spawn("echo", ["hello"]);
  const merge = mergeStream();
  merge.add(spawned.stdout);
  merge.add(spawned.stderr);

  const mergePromise = getStreamPromise(merge, { readable: false });
  const stdoutPromise = getStreamPromise(spawned.stdout);
  const stderrPromise = getStreamPromise(spawned.stderr);
  await Promise.all([mergePromise, stdoutPromise, stderrPromise]);
  console.log("done");
})();
```

The problems are:
- `merge` is both `Readable` and `Writable`, but we want to wait only for `Writable` part to finish, so a `{ readable: false }` has to be passed to `eos`. `stdout` and `stderr` are only `Readable`, so nothing has to be passed.
- Like `Stream.finish`, the function to clean the event listeners added is returned when `eos` is called. If this wasn't the case, we could use `util.promisify` on this, but in this case if we use it then we can't cleanup (the cleanup function is not passed to the callback).

**Comment by ehmicky** [comment] 2019-07-15 10:22
About `stream.resume()` it seems that `duplexA.pipe(duplexB)` puts `duplexA` in flowing mode but not `duplexB`, which actually makes sense. So this is normal that `stdout` and `stderr` are in flowing mode (since they are piped to `all`) but not `all` itself. As you mention `all.resume()` changes the events being emitted, but this is a workaround, not the real solution.

The fix is to listen to all events indicating the stream has ended, as you mention. Using `end-of-stream` is a good idea.

I think you might be able to simplify the code above:

```js
const getStreamPromise = (stream, {readable}) => {
  return new Promise((resolve, reject) => {
    const cleanListeners = eos(stream, {readable}, error => {
      cleanListeners();
      if (err) return reject(err);
      resolve();
    };
  });
};
```

I checked and it passes all tests.

Now crazy idea: why do we need to wait for streams to end at all when `buffer` is `false`? When a child process with `stdio: 'pipe'` exits, it destroys its streams. When `buffer` is `false` and `stdio` is `'pipe'`, shouldn't we only wait for the child process to exit? 

```js
const getStreamPromise = (stream, {encoding, buffer, maxBuffer}) => {
	if (!stream || !buffer) {
		return;
	}

	if (encoding) {
		return getStream(stream, {encoding, maxBuffer});
	}

	return getStream.buffer(stream, {maxBuffer});
};
```

**Comment by tiagonapoli** [comment] 2019-07-15 12:56
> Now crazy idea: why do we need to wait for streams to end at all when buffer is false? When a child process with stdio: 'pipe' exits, it destroys its streams. When buffer is false and stdio is 'pipe', shouldn't we only wait for the child process to exit?

I think this is a good idea. But there's a situation we have to consider, at least to document for the users: I made an example that the process never ends if the `stdout` and `stderr` aren't consumed. In the case of `execa`, the `.all` has to be resumed by the user as well (not only `stdout` and `stderr`), otherwise the process may never end:
```javascript
const eos = require("end-of-stream");
const { spawn } = require("child_process");

const getStreamPromise = (stream, { readable, name }) => {
  return new Promise((resolve, reject) => {
    const cleanListeners = eos(stream, { readable }, err => {
      console.log(`${name} done`);
      cleanListeners();
      if (err) return reject(err);
      resolve();
    });
  });
};

const getSpawnedPromise = proc => {
  return new Promise((resolve, reject) => {
    proc.once("close", () => {
      resolve();
    });

    proc.once("error", error => {
      reject(error);
    });
  });
};

(async () => {
  // 1GB output
  const spawned = spawn("python", [
    "-c",
    "import sys; print('a' * 1000000000); sys.stdout.flush();"
  ]);

  const procDone = getSpawnedPromise(spawned);

  // when each stream is done a message `${stream name} done` will be printed
  const stdoutPromise = getStreamPromise(spawned.stdout, { name: "stdout" });
  const stderrPromise = getStreamPromise(spawned.stderr, { name: "stderr" });

  // spawned.stdout.resume();
  await procDone;
  // this is never printed if spawned.stdout.resume is not called
  console.log("done process");

  await stdoutPromise;
  await stderrPromise;
  console.log("all done");
})();
```

Using `merge-stream`:
```javascript
const eos = require("end-of-stream");
const mergeStream = require("merge-stream");
const { spawn } = require("child_process");

const getStreamPromise = (stream, { readable, name }) => {
  return new Promise((resolve, reject) => {
    const cleanListeners = eos(stream, { readable }, err => {
      console.log(`${name} done`);
      cleanListeners();
      if (err) return reject(err);
      resolve();
    });
  });
};

const getSpawnedPromise = proc => {
  return new Promise((resolve, reject) => {
    proc.once("close", () => {
      resolve();
    });

    proc.once("error", error => {
      reject(error);
    });
  });
};

(async () => {
  // 1GB output
  const spawned = spawn("python", [
    "-c",
    "import sys; print('a' * 1000000000); sys.stdout.flush();"
  ]);

  const merge = mergeStream();
  merge.add(spawned.stdout);
  merge.add(spawned.stderr);

  const procDone = getSpawnedPromise(spawned);

  // when each stream is done a message `${stream name} done` will be printed
  const mergePromise = getStreamPromise(merge, {
    readable: false,
    name: "merge"
  });
  const stdoutPromise = getStreamPromise(spawned.stdout, { name: "stdout" });
  const stderrPromise = getStreamPromise(spawned.stderr, { name: "stderr" });

  merge.resume();
  await procDone;
  // this is never printed if merge.resume is not called
  console.log("done process");

  await stdoutPromise;
  await stderrPromise;
  await mergePromise;
  console.log("all done");
})();

```

I think this is because `stdout` `Writable` part is paused in `child_process` internal, because the stream reaches its limit without being consumed by its `Readable` part. If it's not consumed, the process is stuck without ending. About `all.resume`, since a pipe is being done, if its `Readable` part is not resumed, the `Writable` part will reach its limit and will pause `stdout` and `stderr`, so `all` has to be consumed too.

**Comment by ehmicky** [comment] 2019-07-15 14:26
> I think this is because stdout Writable part is paused in child_process internal, because the stream reaches its limit without being consumed by its Readable part. If it's not consumed, the process is stuck without ending. 

Are you sure that's the reason? Do you mean the `highWaterMark` by "limit"? When I manually set `_readableState.highWaterMark` and `_writableState.highWaterMark` to `10000000000`, the child process is still freezing. I'm not sure whether manually changing `highWaterMark` is meant to be working though.

> About all.resume, since a pipe is being done, if its Readable part is not resumed, the Writable part will reach its limit and will pause stdout and stderr, so all has to be consumed too.

Correct me if I'm wrong but this should only be a problem when `buffer` is `false`, right? When `buffer` is `true`, `get-stream` will read `stdout`, `stderr` and `all`, so `all` should be consumed. Now when `buffer` is `false`, it seems like at the moment, a `stdout` or `stderr` higher than `highWaterMark` (default `16KB`) would pause `stdout` or `stderr` indeed, unless `all` is being consumed. Is this what you meant?

**Comment by ehmicky** [comment] 2019-07-15 14:37
It seems like your first example fails when output is `212992` bytes (`13*(2**14)`). `212991` works.

**Comment by tiagonapoli** [comment] 2019-07-15 14:44
> Correct me if I'm wrong but this should only be a problem when buffer is false, right?  When buffer is true, get-stream will read stdout, stderr and all, so all should be consumed.

Yes, I think the problem is only when `buffer` is `false`, when `all` is not consumed by the user. When `buffer` is true then `get-stream` will consume all then I think there should be no problems.

> Now when buffer is false, it seems like at the moment, a stdout or stderr higher than highWaterMark (default 16KB) would pause stdout or stderr indeed, unless all is being consumed. Is this what you meant?
Exactly. I think `all` pauses `stdout` and `stderr` because `all` is not being consumed, so it can't receive more data, otherwise its buffer would exceed its `highWaterMark`.

> Basically the bottom line is that when buffer is false and the output is bigger than 16KB, the child process will wait until stdout, stderr and all are consumed?

Actually I was doing some tests on the code example I gave and there were three different situations, which happen with increasingly output sizes:
  - Both process and merge stream ends
  - The process does end but merge stream doesn't
  - The process doesn't end

**Comment by tiagonapoli** [comment] 2019-07-15 14:53
> It seems like the limit for your first example is `net.core.rmem_max`.
> 
> ```js
> const spawned = spawn("python", [
>   "-c",
>   // 212991 works
>   "import sys; print('a' * 212992); sys.stdout.flush();"
> ]);
> ```
> 
> ```
> $ sysctl net.core.rmem_max
> net.core.rmem_max = 212992
> ```
> 
> This setting seems to be mostly network-related, but maybe it's used by file descriptors too. In any case, the limit looks deterministic, whether it's set by OS or by Node.js

Wow! Nice discovery! 

Just correcting my code: i think in python `print('...')` will add a `\n` after the message, so I changed the `spawn` excerpt to:
```javascript
  const outputSize = 1000000;
  const spawned = spawn("python3", [
    "-c",
    `import sys; print('a' * ${outputSize}, end=''); sys.stdout.flush();`
  ]);
```

**Comment by ehmicky** [comment] 2019-07-15 15:02
> Exactly. I think all pauses stdout and stderr because all is not being consumed, so it can't receive more data, otherwise its buffer would exceed its highWaterMark. Correction: I think the explanation to this is something like this, but the experiments I made with 16KB, 32KB, etc, didn't show this behavior.

Ok so if we forget about `all` and think about which behavior should be expected there. I think when `buffer` is `false`, `execa()` should not resolve until `stdout` and `stderr` have been consumed. This mirrors how core Node.js is working. If there's pending output, the process should not be considered "done". When the user passes `buffer: false` + `stdio: 'pipe'` (the default), it means they take responsibility for consuming the process output. 

Which means it is ok for the `childProcess` not to end until streams have been consumed. It also means we only need to wait for `childProcess` termination, and not streams termination (since the first one implies the second in that case).

Now `all` is problematic because this would require users to also consume it. It seems like `all` should be an opt-in instead of an opt-out.

What do you think?

**Comment by tiagonapoli** [comment] 2019-07-15 15:10
>  What` do you think?
I agree. Then if the user opts to use `all`, he should take responsibility on consuming it, it just has to be evidenced on the docs that if he doesn't the process may not end.

**Comment by ehmicky** [comment] 2019-07-15 15:22
An example that does not involve Python (so we can use it in tests):

```js
const spawned = spawn("node", ['-e', 'console.log("a".repeat(219264))']);
```

Somehow the limit is slightly more there (at least on my machine).

**Comment by tiagonapoli** [comment] 2019-07-15 15:29
> Somehow the limit is slightly more there (at least on my machine).

Nice! On my machine the limit for this example is 219264 too

**Comment by ehmicky** [comment] 2019-07-15 15:48
Ok so this is a summary of this issue:

## Big `stdout` or `stderr` can make the child process not exit

The child process does not emit the `exit` event (i.e. the `execa()` returned promise does not resolve) when the either `stdout` or `stderr`:
  - is large (more than `219214` bytes on my machine)
  - uses `stdio: 'pipe'` (the default value)
  - is not read

Using `buffer: true` (the default value) reads all streams, so this only happens when `buffer` is `false`.

## `all` must be consumed for the child process to exit, when `stdout` or `stderr` is big

When the conditions above are met, `all` also need to be read, for the same reasons. However `all` is different from `stdout` and `stderr`:
  - it is setup by `execa` not by Node.js core. It's a `PassThrough` that gets both `stdout` and `stderr` as piped input.
  - most users might not be want to consume that stream, as it might be redundant with consuming `stdout` or `stderr`

## Waiting for streams completion when `buffer` is `false` is problematic

When `buffer` is `false` and `stdout`, `stderr` or `all` uses `stdio: 'pipe'` (the default value), we wait for the stream to complete.

However:
  - we are waiting for `end` and `error` events, but should also wait for the `close` and `finish` events.
  - the child process will only end once its streams have completed, so this is unnecessary altogether.

**Comment by ehmicky** [comment] 2019-07-15 15:55
A possible solution would be this. 

When `buffer` is `false` and stream uses `stdio: 'pipe'`:
  - do not wait for the stream completion anymore.
  - users must consume its `stdout` and `stderr`. This is the current documented and expected behavior, so no changes there.

This should also resolve the `all` issues. By consuming `stdout` and `stderr`, `all` should be indirectly "consumed" as well.

What do you think? Did I get something wrong?

**Comment by ehmicky** [comment] 2019-07-15 16:12
Some extra discoveries:
  - when reproducing the above example but using `execa` instead of `child_process` the limit was 10 times higher. I think the reason is because `all` actually consumes `stdout` and `stderr`.
  - `all` does need to consumed, not only `stdout` and `stderr`, so my solution above does not work completely.

```js
const execa = require('.');

const test = async () => {
	const cp = execa('node', ['-e', 'console.log("a".repeat(3_000_000))'], {buffer: false});
	// cp.stdout.resume();
	// cp.stderr.resume();
	// cp.all.resume();
	await cp;
	console.log('done');
};

test();
```

**Comment by ehmicky** [comment] 2019-07-15 16:33
Some tests:

```js
test('buffer: false > promise resolves', async t => {
	await t.notThrowsAsync(execa('echo', ['hello'], {buffer: false}));
});

test('buffer: false > promise does not resolve when output is big and is not read', async t => {
	const {timedOut} = await t.throwsAsync(execa('node', ['-e', 'console.log("a".repeat(3_000_000))'], {buffer: false, timeout: 1e3}));
	t.true(timedOut);
});

test('buffer: false > promise resolves when output is big and is read', async t => {
	const cp = execa('node', ['-e', 'console.log("a".repeat(3_000_000))'], {buffer: false});
	cp.stdout.resume();
	cp.stderr.resume();
	await t.notThrowsAsync(cp);
});

test('buffer: false > promise does not resolve when output is big and "all" is used but not read', async t => {
	const cp = execa('node', ['-e', 'console.log("a".repeat(3_000_000))'], {buffer: false, all: true, timeout: 1e3});
	cp.stdout.resume();
	cp.stderr.resume();
	const {timedOut} = await t.throwsAsync(cp);
	t.true(timedOut);
});

test('buffer: false > promise resolves when output is big and "all" is used and is read', async t => {
	const cp = execa('node', ['-e', 'console.log("a".repeat(3_000_000))'], {buffer: false, all: true});
	cp.stdout.resume();
	cp.stderr.resume();
	cp.all.resume();
	await t.notThrowsAsync(cp);
});

test('buffer: false > promise resolves when output is big but is not pipable', async t => {
	await t.notThrowsAsync(execa('node', ['-e', 'console.log("a".repeat(3_000_000))'], {buffer: false, stdout: 'ignore'}));
});
```

**Comment by tiagonapoli** [comment] 2019-07-15 16:36
> * `all` does need to consumed, not only `stdout` and `stderr`, so my solution above does not work completely.

Yeah, you are right.

I did some experiments using `merge-stream` and `child_process` and the limit was higher too:
```javascript
const eos = require("end-of-stream");
const mergeStream = require("merge-stream");
const { spawn } = require("child_process");

const getStreamPromise = (stream, { readable, name }) => {
  return new Promise((resolve, reject) => {
    const cleanListeners = eos(stream, { readable }, err => {
      console.log(`${name} done`);
      cleanListeners();
      if (err) return reject(err);
      resolve();
    });
  });
};

const getSpawnedPromise = proc => {
  return new Promise((resolve, reject) => {
    proc.once("close", () => {
      resolve();
    });

    proc.once("error", error => {
      reject(error);
    });
  });
};

(async () => {
  const spawned = spawn("node", ["-e", `console.log("a".repeat(${1000000}))`]);

  const merge = mergeStream();
  merge.add(spawned.stdout);
  merge.add(spawned.stderr);

  const procDone = getSpawnedPromise(spawned);

  // when each stream is done a message `${stream name} done` will be printed
  const mergePromise = getStreamPromise(merge, {
    readable: false,
    name: "merge"
  });
  const stdoutPromise = getStreamPromise(spawned.stdout, { name: "stdout" });
  const stderrPromise = getStreamPromise(spawned.stderr, { name: "stderr" });

  // merge.resume();
  await procDone;
  // this is never printed if merge.resume is not called
  console.log("done process");

  await stdoutPromise;
  await stderrPromise;
  await mergePromise;
  console.log("all done");
})();
```

I tested with some sizes on my computer:
  - `1000000`: The process finishes. Sometimes `merge` stream doesn't finish, sometimes it does. Maybe because some memory state of the system.
  - `2000000`: The process sometimes finishes, sometimes doesn't, but the merge stream doesn't finish
  - `3000000`: The process doesn't finish

I think the interaction with `merge-stream` would complicate to find a boundary.

**Comment by ehmicky** [comment] 2019-07-15 16:39
I've done some experiments and the following seems to work:
  - add an `all` boolean option defaulting to `false`
  - not waiting for streams completion anymore

What do you think?

**Comment by tiagonapoli** [comment] 2019-07-15 16:41
> I've done some experiments and the following seems to work:
> 
> * add an `all` boolean option defaulting to `false`
> * not waiting for streams completion anymore
> 
> What do you think?

I think this would solve the problem.

**Comment by ehmicky** [comment] 2019-07-15 16:47
I've added a `feature/all-option` branch with those changes.

What about working together on that branch, would this work for you?

I can do the following: 
  - add documentation in `README`
  - add TypeScript types.
  
Could you help with the following:
  - finish the code and tests if there's anything missing
  - doing some test to make sure we're not committing a mistake with this :) This a breaking change (since some users now need to opt-in to use `all`) so we need to be extra careful.
  - open a PR summing up the problem as simple as possible so that @sindresorhus can get it without going through this issue.

What do you think?

**Comment by tiagonapoli** [comment] 2019-07-15 17:21
> What about working together on that branch, would this work for you?
Seems good to me :)

**Comment by ehmicky** [comment] 2019-07-15 18:24
Thanks!

I've just finished all my changes on the branch. Let me know if anything looks wrong :)

**Comment by tiagonapoli** [comment] 2019-07-15 19:12
The tests worked on my machine. Did some tests for the bugs we found and everything seemed ok

**Comment by ehmicky** [comment] 2019-07-16 08:38
Would you be interested in forking the branch then opening the PR and taking it from there? Meaning:
  - adding the PR description for @sindresorhus to understand the reasons behind this breaking change
  - fixing what might arise during the code review by @sindresorhus

**Comment by tiagonapoli** [comment] 2019-07-16 13:14
Done :)

**Closed** 2019-07-31 16:57 UTC
