### ISSUE TITLE
`childProcess.all` interleaved result might be out-of-order

### ISSUE THREAD

**Issue by F3n67u** [sindresorhus/execa#502] opened 2022-06-12 06:13 UTC
## Reproduction step

```console
$ cat noop-132.mjs                                     
#!/usr/bin/env node
import process from 'node:process';

process.stdout.write('1');
process.stderr.write('3');
process.stdout.write('2');
$ cat test.mjs    
import {execa} from 'execa';

const { all } = await execa('./noop-132.mjs', {all: true });
console.log(all);
$ node test.mjs
123
```

## Expect behavior

`node test.mjs` should output `132` as the README says:

> [Get interleaved output](https://github.com/sindresorhus/execa#all) from stdout and stderr similar to what is printed on the terminal. [(Async only)](https://github.com/sindresorhus/execa#execasyncfile-arguments-options)

```console
$ ./noop-132.mjs         
132
```

## Actual behavior

`node test.mjs`  output `123`

## Environment Info

```console
$ node -v      
v18.2.0
$ npm ls execa  
test@1.0.0 /Users/feng/test
└── execa@6.1.0
```

**Comment by sindresorhus** [comment] 2022-06-12 09:18
Note that `process.stdout.write` is not guaranteed to be synchronous.

See Node.js docs: https://nodejs.org/api/process.html#a-note-on-process-io

**Comment by F3n67u** [comment] 2022-06-12 09:25
@sindresorhus Thanks for the reply. The original problem is when running a shell script, the output order is not correct:

```
$ npm ls execa 
test@1.0.0 /Users/feng/test
└── execa@6.1.0
$ cat script.sh
echo test1;
echo test2;
echo test3;
echo test4;
echo test5;
dfgyfhgdtfgsdfsdf;
echo test6;
echo test7;
echo test8;
echo test9;
echo test10;
$ cat test.mjs     
import {execa} from 'execa';

const { all } = await execa('./script.sh', {all: true });
console.log(all);
$ node test.mjs
test1
test2
test3
test4
test5
test6
test7
test8
test9
test10
./script.sh: line 6: dfgyfhgdtfgsdfsdf: command not found
```

The correct order would actually be:

```console
test1
test2
test3
test4
test5
./script.sh: line 6: dfgyfhgdtfgsdfsdf: command not found
test6
test7
test8
test9
test10
```

Is this example could be judged as a validated bug report?

**Comment by sindresorhus** [comment] 2022-06-12 09:37
I don't have an answer for you. The implementation is quite simple: https://github.com/sindresorhus/execa/blob/071d0a282a14633493e9d8b4e5b686c43da64368/lib/stream.js#L19-L35

Some possible reasons:

- Bug in the `merge-stream` package we use.
- Bug in Node.js streams (happens more often than you would think).
- script.sh behaving differently when used in the terminal and when used as a sub process.

**Comment by lydell** [comment] 2022-07-10 19:12
> script.sh behaving differently when used in the terminal and when used as a sub process.

This Python script shows we can rule that one out. (Uses the same `noop-132.mjs` file as in the first post.)

```py
import subprocess
task = subprocess.Popen(['./noop-132.mjs'], stdout=subprocess.PIPE, stderr=subprocess.STDOUT, encoding="utf8")
print(task.stdout.read())
```

```
❯ python3 tst.py
132
```

**Comment by ehmicky** [comment] 2023-12-18 02:58
The problem is this: when using the `all` option, we currently guarantee the order of the `stdout` writes (on their own), of the `stderr` writes (on their own), but not the order of the interleaving of those two.

In other terms, `stdout` and `stderr` are both merged to the same destination (`all`), but they might do it at different paces. 

Implementation-wise, this feature mostly rely on [`@sindresorhus/merge-streams`](https://github.com/sindresorhus/merge-streams), so any fix would probably need to be done on that dependency.

https://github.com/sindresorhus/execa/blob/fcf648e21b6ccc9ec279fb758318ed7581f02fc6/lib/stream.js#L6-L13

Since this is a timing / race condition related issue involving streams, reproducing in CI will be difficult. However, I can reproduce it locally using @F3n67u's first example.

**Comment by ehmicky** [comment] 2023-12-23 18:10
I did some additional research into this. The bottom line is: this behavior is inherited from Node.js and I do not think we cannot change, although users can use some workarounds.

The core of the issue can be reproduced with this sample, which is a simplification of what Execa does under the hood:

```js
// example.js
import process from 'node:process';

process.stdout.write('1');
process.stderr.write('2');
process.stdout.write('3');
```

```js
// run.js
import {spawn} from 'node:child_process';

const childProcess = spawn('node', ['example.js']);
childProcess.stdout.on('data', value => {
  console.log('stdout', value.toString());
})
childProcess.stderr.on('data', value => {
  console.log('stderr', value.toString());
})
```

When calling `node run.js`, the output is:

```
stdout 13
stderr 2
```

The two `process.stdout.write()` got merged into a single `data` event by Node.js. This is happening for performance reasons: Node.js buffers the write calls done in the same microtask.

This is done at the core Node.js level, and there is not much Execa can do at the process spawning level. Also, since is done for performance reasons, it is mostly beneficial, albeit it creates this out-of-order issue.

The workaround is to delay writes to a different microtask. For example:

```js
// example.js
import process from 'node:process';

process.stdout.write('1');
process.stderr.write('2');
process.nextTick(() => {
  process.stdout.write('3');
})
```

Results in:

```
stdout 1
stderr 2
stdout 3
```

The conclusion is: 
  - If a child process's `stdout` and `stderr` are both written to in the same microtask
  - Then `childProcess.all` will show first the `stdout` writes (in order), then the `stderr` writes (in order), or the other way around, but not interleaved

**Closed** 2023-12-23 23:54 UTC
