### ISSUE TITLE
execa does not respect $PATH variable

### ISSUE THREAD

**Issue by lucasbraun** [sindresorhus/execa#153] opened 2018-11-02 13:53 UTC
I have two installations of git and `execa` seems to pick the wrong one, not respecting `$PATH` correctly, while `child-process` does it correctly (even if I explicitly remove `/usr/bin` from `$PTAH` and add my desired path twice, once in the beginning and once in the end):

```
$ /usr/bin/git --version 
git version 1.8.3.1
$ /opt/rh/rh-git29/root/usr/bin/git --version
git version 2.9.3
$ echo $PATH
/opt/rh/rh-git29/root/usr/bin:/bin:/usr/local/bin:/opt/rh/rh-git29/root/usr/bin
$ cat ./index.js
const execa = require('execa');
(async () => {
    const {stdout} = await execa('git', ['--version']);
    console.log(stdout);
    //=> 'unicorns'
})();
const execFile = require('child_process').execFile;
const child = execFile('git', ['--version'], (error, stdout, stderr) => {
    if (error) {
        console.error('stderr', stderr);
        throw error;
    }
    console.log('stdout', stdout);

});
$ node ./index.js
git version 1.8.3.1
stdout git version 2.9.3
```

I am missing something here?

**Comment by ammarbinfaisal** [comment] 2019-03-13 08:46
@lucasbraun This doesn't appear to be problem with execa. execa is an alternative to childProcess.spawn(actually better than using it) and you shouldn't compare execFile's output with execa. Try using childProcess.spawn instead of execa and it would show the same result. Also, have a look at this nodejs/node#12986

**Comment by ehmicky** [comment] 2019-03-13 10:06
@ammarbinfaisal `childProcess.spawn` is the base for all other `childProcess` methods variants including `execFile()`. See the [Node.js source](https://github.com/nodejs/node/blob/master/lib/child_process.js#L176).

**Comment by ehmicky** [comment] 2019-03-13 10:14
@lucasbraun There has been few changes to the code handling `env` lately, can you use the latest commit (not latest release) of execa and confirm this is still a bug when ?

Also could you try the following code instead?

```js
const execa = require('execa');
const childProcess = require('child_process');

console.log(execa.sync('echo $PATH', { shell: true }).stdout)
console.log(childProcess.spawnSync('echo $PATH', { shell: true, encoding: 'utf8' }).stdout)
```

**Comment by lucasbraun** [comment] 2019-03-13 10:56
Thanks, @ehmicky for your help with this. Unfortunately, the problem remains. I just checked with `execa` from master (`7f8d911153c475d75da0925adf2db40cbe13a98a`). While echoing the PATH does the right thing, it seems that the PATH is still not properly used:

```
$ cat test-lucas.js 
const execa = require('.');
const childProcess = require('child_process');

console.log("PATH with execa:", execa.sync('echo $PATH', { shell: true }).stdout);
console.log("git with execa:", execa.sync('git', ['--version'], { shell: true }).stdout);

console.log("PATH with child process:", childProcess.spawnSync('echo $PATH', { shell: true, encoding: 'utf8' }).stdout);
console.log("git with child process:", childProcess.spawnSync('git', ['--version'], { shell: true, encoding: 'utf8' }).stdout);
```

```
$ node test-lucas.js 
PATH with execa: /scratch/lbraun/execa/node_modules/.bin:/scratch/lbraun/node_modules/.bin:/scratch/node_modules/.bin:/node_modules/.bin:/usr/bin:/opt/rh/rh-git29/root/usr/bin:/scratch/opt/bin:/bin:/usr/bin:/usr/dev_infra/platform/bin:/usr/dev_infra/generic/bin:/usr/local/bin:/usr/X11R6/bin:/usr/local/ade/bin
git with execa: git version 1.8.3.1
PATH with child process: /opt/rh/rh-git29/root/usr/bin:/scratch/opt/bin:/bin:/usr/bin:/usr/dev_infra/platform/bin:/usr/dev_infra/generic/bin:/usr/local/bin:/usr/X11R6/bin:/usr/local/ade/bin

git with child process: git version 2.9.3
```

Here is my environment:
```
$ cat /etc/os-release
NAME="Oracle Linux Server"
VERSION="7.4"
ID="ol"
VERSION_ID="7.4"
PRETTY_NAME="Oracle Linux Server 7.4"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:7:4:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 7"
ORACLE_BUGZILLA_PRODUCT_VERSION=7.4
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=7.4

$ node --version
v8.12.0

execa version: 7f8d911153c475d75da0925adf2db40cbe13a98a
```

I guess that it might be reproduce the problem on my OS, but I don't see why this should be an OS-specific problem. The problem should be reproducible on any OS where you install more than one version of git.

**Comment by ehmicky** [comment] 2019-03-13 11:13
You never know when a problem might be OS-specific unless you're very familiar with the implementation code, so it's better to be on the safe side :) Also the Node.js version is always a good idea to include in any Git issue.

Just to be 100% sure, could you please paste your code above but with `'git --version'` instead of `git, ['--version']`? The `shell` option allows you to do that, and it might give different results (not likely but just in case it does).

**Comment by ehmicky** [comment] 2019-03-13 11:16
Also if you add a third command output for both `execa()` and `child_process.spawn()`: `which git`

**Comment by lucasbraun** [comment] 2019-03-13 11:56
Yes, I can :-)

```
$ cat test-lucas.js 
const execa = require('.');
const childProcess = require('child_process');
console.log("PATH with execa:", execa.sync('echo $PATH', { shell: true }).stdout);
console.log("git with execa:", execa.sync('git', ['--version'], { shell: true }).stdout);
console.log("git --version with execa:", execa.sync('git --version', { shell: true }).stdout);
console.log("which git with execa:", execa.sync('which git', { shell: true }).stdout);

console.log("PATH with child process:", childProcess.spawnSync('echo $PATH', { shell: true, encoding: 'utf8' }).stdout);
console.log("git with child process:", childProcess.spawnSync('git', ['--version'], { shell: true, encoding: 'utf8' }).stdout);
console.log("git --version with child process:", childProcess.spawnSync('git --version', { shell: true, encoding: 'utf8' }).stdout);
console.log("which git with child process:", childProcess.spawnSync('which git', { shell: true, encoding: 'utf8' }).stdout);


$ node test-lucas.js                                                                                                                    
PATH with execa: /scratch/lbraun/execa/node_modules/.bin:/scratch/lbraun/node_modules/.bin:/scratch/node_modules/.bin:/node_modules/.bin:/usr/bin:/opt/rh/rh-git29/root/usr/bin:/scratch/opt/bin:/bin:/usr/bin:/usr/dev_infra/platform/bin:/usr/dev_infra/generic/bin:/usr/local/bin:/usr/X11R6/bin:/usr/local/ade/bin
git with execa: git version 1.8.3.1
git --version with execa: git version 1.8.3.1
which git with execa: /usr/bin/git
PATH with child process: /opt/rh/rh-git29/root/usr/bin:/scratch/opt/bin:/bin:/usr/bin:/usr/dev_infra/platform/bin:/usr/dev_infra/generic/bin:/usr/local/bin:/usr/X11R6/bin:/usr/local/ade/bin

git with child process: git version 2.9.3

git --version with child process: git version 2.9.3

which git with child process: /opt/rh/rh-git29/root/usr/bin/git
```

**Comment by ehmicky** [comment] 2019-03-13 12:18
I think the PR I just opened here: https://github.com/sindresorhus/npm-run-path/pull/5 should solve your problem. `npm-run-path` is the module used by `execa` that probably is creating this bug. 

This needs to be reviewed by @sindresorhus first though.

**Comment by lucasbraun** [comment] 2019-03-13 12:33
OK, thanks a lot! Looking forward to see whether it does fix the problem. That would be awesome!

**Comment by ehmicky** [comment] 2019-03-13 12:37
I think the issue here is that `execa` is prepending the directory of `process.execPath` to `$PATH`. This is to allow users firing global binaries. In your case that directory is `/usr/bin`, which leads `/usr/bin` being present twice in your `$PATH`.

Until the problem is merged, using `nvm` would probably solve your issue as `process.execPath` would then be modified by `nvm`.

**Comment by ehmicky** [comment] 2019-05-24 12:05
I thought of a way to move forward with this: see https://github.com/sindresorhus/npm-run-path/pull/5#issuecomment-495595101

**Comment by ehmicky** [comment] 2019-06-24 11:50
@lucasbraun If I understood your problem correctly, using the [`preferLocal: false` option](https://github.com/sindresorhus/execa#preferlocal) should solve it, could you confirm this?

We are considering changing its default value from `true` to `false` (#314).

**Comment by lucasbraun** [comment] 2019-06-24 12:00
Yes, it does. Thanks a lot for fixing!

**Comment by ehmicky** [comment] 2019-06-24 15:49
Closing this thanks to #314.

**Closed by ehmicky** 2019-06-24 15:49 UTC
Labels: bug, help wanted

**Comment by Glandos** [comment] 2019-07-12 14:01
My solution:
```sh
export PATH
```
I see that the original poster uses Software Collections. I've run into the very same issue with fish and `set -g -p PATH /custom/bin`, until I found that in a bare `node` interpreter, `process.env.PATH` is `undefined`.
When using `preferLocal` to `true`, the environment is set by `npm-run-path` which does the right thing: it appends the current path to some local path.

It seems to be a trick of fish shell:
```sh
> python3 -c 'import os; print(os.environ["PATH"])'
/home/user/.local/bin/:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
> set -g -p PATH /truc
> python3 -c 'import os; print(os.environ["PATH"])'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.7/os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'PATH'
> set -x -p PATH /truc
> python3 -c 'import os; print(os.environ["PATH"])'
/truc:/truc:/home/user/.local/bin/:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
```
Node has (fortunately) the same behavior.

And if for some reason, `PATH` is not exported, you'll run into the very same issue.
