### ISSUE TITLE
Windows: Execa is leaking processes when used with readline

### ISSUE THREAD

**Issue by Ciantic** [sindresorhus/execa#429] opened 2020-06-08 21:45 UTC
Repro is here: https://github.com/Ciantic/execa-readline-problems 

There is also a long spanning discussion because it leads to snowpack leaking processes in Windows: https://www.pika.dev/npm/snowpack/discuss/295

It seems like the cleanup is not working correctly when readline is used. Also I think there is some race condition here, because I have managed to make scripts where the execa cleanup happens sometimes, but sometimes not. So it's not deterministic.

node --version: v12.18.0

**Comment by sindresorhus** [comment] 2020-06-09 07:22
Can you check whether the problem is also reproducible on Node.js 14? I don't have a Windows VM right now, so I cannot test.

Can you also try replacing `const myProcess = execa('tsc --noEmit --watch', {shell: true, cleanup: true});` with `const myProcess = execa.command('tsc --noEmit --watch', {cleanup: true});`?

**Comment by Ciantic** [comment] 2020-06-12 22:07
I tested this in the VM. The Windows Sandbox with Windows 10 2004. It's still reproducible with this setup, so yes I would conclude it's broken somehow.

node:
v12.18.0

I updated my repository with repro, nothing that changes the behavior.

**Comment by ManiacDC** [comment] 2020-08-14 15:43
I can also reproduce this, Windows 10 1909
node v12.14.1

Tried from both bash and powershell

**Comment by ManiacDC** [comment] 2020-08-14 15:49
This issue seems like it might be the root cause of:
https://github.com/lerna/lerna/issues/2284

**Comment by ManiacDC** [comment] 2020-08-14 16:23
Worth noting, I can't reproduce this using the same example code, but with execa 1.0.0 (which is what lerna uses, so it might not be the root cause of lerna/lerna#2284 anyway).

**Comment by Ciantic** [comment] 2020-08-14 19:52
It's sometimes not reproducible, so if you managed to reproduce it once, it might still be reproducible.

**Comment by ehmicky** [comment] 2020-08-14 21:27
More information in #433 (which seems to be a duplicate issue).

Could you try to pass the `windowsHide: false` option to Execa and see if this solves the problem?

**Comment by ManiacDC** [comment] 2020-08-17 12:47
I just tested this specific issue with windowsHide: false and it fixed this one too, so #433 and this issue do appear to be duplicates.

**Comment by ehmicky** [comment] 2020-08-18 15:46
Thanks for checking this out @ManiacDC! Closing this issue as duplicate then.

**Closed by ehmicky** 2020-08-18 15:46 UTC
