### ISSUE TITLE
cross-spawn-async@2.2.4 is deprecated

### ISSUE THREAD

**Issue by deepsweet** [sindresorhus/execa#57] opened 2016-09-27 09:19 UTC
Hi. Just got this message:

> npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!

Is it relevant here?

**Comment by sindresorhus** [comment] 2016-09-27 09:21
Duplicate of https://github.com/sindresorhus/execa/issues/50.

**Closed by sindresorhus** 2016-09-27 09:21 UTC
